# Generated by Django 4.1.5 on 2023-01-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Страница география',
                'verbose_name_plural': 'Страница география',
            },
        ),
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Страница востребованность',
                'verbose_name_plural': 'Страница востребованность',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Навзвание')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='profession_img/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Страница навыки',
                'verbose_name_plural': 'Страница навыки',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('csv_file', models.FileField(upload_to='csv/', verbose_name='Csv файл')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('geography_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geography_id', to='app.geography')),
                ('importance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='importance_id', to='app.importance')),
                ('skill_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='skill_id', to='app.skill')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
    ]
